name: flutter_boilerplate[ana;uze and test]
on:
  push:
    branches:
      - main
    pull_requests:
      jobs:
        lint:
          name: Checking the code style
          runs_on: ubuntu-latest
          steps:
            - name: Clone flutter repo
              uses: subosito/flutter-action@v1
              with:
                flutter-version: '3.0.0'
                channel: 'stable'

            - name: Checkout code
              used: actions/checkout@v2

            - name: Install dependencies
              run: |
                flutter clean
                flutter packages get

            - name: analyze code
              run: flutter analyze

                
                