name: flutter_boilerplate[analyze and test]
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Checking the code style
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repo
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.0"
          channel: "stable"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter clean && flutter pub get

      - name: analyze code
        run: flutter analyze
